flags: {}
extra-include-dirs:
- /usr/local/opt/mpfr/include
extra-package-dbs: []
extra-lib-dirs:
- /usr/local/opt/mpfr/lib
packages:
- '.'
extra-deps:
- distributed-process-0.6.6
compiler: ghc-8.0.1
resolver: lts-7.10
